export type PracticeTextCategory = "genel" | "hukuki" | "resmi";

export type PracticeTextDifficulty = "baslangic" | "orta" | "ileri";

export interface PracticeText {
  id: string;
  category: PracticeTextCategory;
  title: string;
  body: string;
  difficulty: PracticeTextDifficulty;
  /** True for texts generated by the weakness-driven drill generator, not seed content. */
  generated?: boolean;
}
